definitions:
  dto.ArticleInput:
    properties:
      category_id:
        example: 1
        type: integer
      content:
        example: 我想去看看
        type: string
      title:
        example: 世界辣么大
        type: string
    required:
    - category_id
    - content
    - title
    type: object
  dto.ArticleItemOutput:
    properties:
      created_at:
        description: 创建时间
        type: string
      id:
        description: id
        type: integer
      title:
        description: 标题
        type: string
      visits:
        description: 访问量
        type: integer
    type: object
  dto.ArticleListOutput:
    properties:
      list:
        description: 列表
        items:
          $ref: '#/definitions/dto.ArticleItemOutput'
        type: array
      total:
        description: 数量
        type: integer
    type: object
  dto.ArticleOutput:
    properties:
      category_id:
        description: 分类id
        type: integer
      category_name:
        description: 分类name
        type: string
      content:
        description: 内容
        type: string
      created_at:
        description: 创建时间
        type: string
      id:
        description: id
        type: integer
      title:
        description: 标题
        type: string
      visits:
        description: 访问量
        type: integer
    type: object
  dto.ArticleUpdateInput:
    properties:
      category_id:
        example: 1
        type: integer
      content:
        example: 我想去看看
        type: string
      id:
        description: id
        example: 1
        type: integer
      title:
        example: 世界辣么大
        type: string
    required:
    - id
    type: object
  dto.CategoryInput:
    properties:
      name:
        example: 编程
        type: string
    required:
    - name
    type: object
  dto.CategoryUpdate:
    properties:
      id:
        description: id
        example: 1
        type: integer
      name:
        example: 编程
        type: string
    required:
    - id
    - name
    type: object
  dto.LoginInput:
    properties:
      email:
        description: 邮箱
        example: abc123@qq.com
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
    required:
    - email
    - password
    type: object
  dto.Profile:
    properties:
      avatar:
        description: 头像
        type: string
      email:
        description: 邮箱
        type: string
      id:
        description: id
        type: integer
      name:
        description: 昵称
        type: string
      phone:
        type: string
    type: object
  dto.RegisterInput:
    properties:
      email:
        description: 邮箱
        example: abc123@qq.com
        type: string
      name:
        description: 昵称
        example: 小明
        type: string
      password:
        description: 密码
        example: "123456"
        type: string
      phone:
        description: 手机号
        example: "19999999999"
        type: string
    required:
    - email
    - name
    - password
    type: object
  dto.TagInput:
    properties:
      name:
        description: 标签名
        example: mysql
        type: string
    required:
    - name
    type: object
  dto.TagListOutput:
    properties:
      list:
        items:
          $ref: '#/definitions/dto.TagOutput'
        type: array
      total:
        type: integer
    type: object
  dto.TagOutput:
    properties:
      id:
        description: id
        type: integer
      name:
        description: 标签名
        type: string
    type: object
  dto.TagUpdate:
    properties:
      id:
        description: id
        example: 1
        type: integer
      name:
        description: 标签名
        example: mysql
        type: string
    required:
    - id
    - name
    type: object
info:
  contact: {}
  license: {}
paths:
  /api/v1/articles:
    get:
      description: 文章列表
      parameters:
      - description: 分类id
        in: query
        name: category_id
        type: integer
      - description: 搜索关键词
        in: query
        name: title
        type: string
      - description: 条数
        in: query
        name: page_size
        required: true
        type: string
      - description: 页码
        in: query
        name: page_no
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.ArticleListOutput'
      summary: 文章列表
      tags:
      - 文章
    patch:
      description: 修改文章
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ArticleUpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"","msg":"ok"}'
          schema:
            type: json
      security:
      - ApiKeyAuth: []
      summary: 修改文章
      tags:
      - 文章
    post:
      description: 写文章
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ArticleInput'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"","msg":"ok"}'
          schema:
            type: json
      security:
      - ApiKeyAuth: []
      summary: 写文章
      tags:
      - 文章
  /api/v1/articles/{id}:
    delete:
      description: 删除文章
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"","msg":"ok"}'
          schema:
            type: json
      summary: 删除文章
      tags:
      - 文章
    get:
      description: 文章详情
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.ArticleOutput'
      summary: 文章详情
      tags:
      - 文章
  /api/v1/categories:
    get:
      description: 分类列表
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.TagListOutput'
      summary: 分类列表
      tags:
      - 分类
    patch:
      description: 修改分类
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CategoryUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"","msg":"ok"}'
          schema:
            type: json
      security:
      - ApiKeyAuth: []
      summary: 修改分类
      tags:
      - 分类
    post:
      description: 创建分类
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.CategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"","msg":"ok"}'
          schema:
            type: json
      security:
      - ApiKeyAuth: []
      summary: 创建分类
      tags:
      - 分类
  /api/v1/categories/{id}:
    delete:
      description: 删除分类
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 分类ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"","msg":"ok"}'
          schema:
            type: json
      summary: 删除分类
      tags:
      - 分类
  /api/v1/login:
    post:
      description: 用户登录
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"token","msg":"ok"}'
          schema:
            type: json
      summary: 登录
      tags:
      - 用户接口
  /api/v1/register:
    post:
      description: 用户注册
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":null,"msg":"ok"}'
          schema:
            type: json
      summary: 注册
      tags:
      - 用户接口
  /api/v1/tags:
    get:
      description: 标签列表
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.TagListOutput'
      summary: 标签列表
      tags:
      - 标签
    post:
      description: 创建标签
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.TagInput'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"","msg":"ok"}'
          schema:
            type: json
      security:
      - ApiKeyAuth: []
      summary: 创建标签
      tags:
      - 标签
    put:
      description: 修改标签
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.TagUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"","msg":"ok"}'
          schema:
            type: json
      security:
      - ApiKeyAuth: []
      summary: 修改标签
      tags:
      - 标签
  /api/v1/tags/{id}:
    delete:
      description: 删除标签
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 标签ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":"","msg":"ok"}'
          schema:
            type: json
      summary: 删除标签
      tags:
      - 标签
  /api/v1/user:
    get:
      description: 获取个人信息
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/dto.Profile'
      security:
      - ApiKeyAuth: []
      summary: 个人信息
      tags:
      - 用户接口
  /ping:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"pong"}'
          schema:
            type: string
      summary: ping
swagger: "2.0"
